### ISSUE TITLE
Redirect from www to non-www and the other way around

### ISSUE THREAD

**Issue by gregory90** [mesosphere/marathon-lb#154]
...or it should be done at the application level?

**Comment by brndnmtthws** [comment]
Can you elaborate? Are you talking about redirecting domains?

**Comment by gregory90** [comment]
Yes. For example I want to be able to redirect https://www.domain.com to
https://domain.com

**Comment by brndnmtthws** [comment]
You can put a rule in your backend:

```json
{
  "id":"app",
  "labels":{
    "HAPROXY_GROUP":"external",
    "HAPROXY_0_VHOST":"www.domain.com,domain.com",
    "HAPROXY_0_BACKEND_HEAD":"backend {backend}\n  balance {balance}\n  mode {mode}\n  redirect prefix http://domain.com code 301 if { hdr(host) -i www.domain.com }\n"
  }
}
```

**Comment by gregory90** [comment]
It does fail with:
```
Traceback (most recent call last):
  File "/marathon-lb/marathon_lb.py", line 1178, in do_reset
    self.__templater)
  File "/marathon-lb/marathon_lb.py", line 1130, in regenerate_config
    ssl_certs, templater), config_file)
  File "/marathon-lb/marathon_lb.py", line 334, in config
    mode=app.mode
KeyError: ' hdr(host) -i www'
```

**Comment by bogdangi** [comment]
Hi, this waht I did to make it work
    
```
"HAPROXY_0_BACKEND_HEAD": "backend {backend}\n  balance {balance}\n  mode {mode}\n  acl host_www    hdr_beg(host) -i www \n  redirect prefix https://www.domain.com code 302 unless host_www \n"
```
