### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645) after upgrading 1.2.0 -> 1.2.1

### ISSUE THREAD

**Issue by Nihn** [mesosphere/marathon-lb#178]
Hi,

I'm using custom certificates by mounting `/etc/ssl` into `marathon-lb` container. It worked till version 1.2.1. I know that there was change "Dropped support for TLS 1.0 by default " by my certificates are in version 3.0.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 604, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/marathon-lb/marathon_lb.py", line 1426, in <module>
    args.ssl_certs)
  File "/marathon-lb/marathon_lb.py", line 1326, in process_sse_events
    for event in events:
  File "/marathon-lb/marathon_lb.py", line 233, in get_event_stream
    headers=headers, auth=self.__auth)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/marathon-lb/marathon_lb.py", line 1432, in <module>
    logger.error("Reconnecting in {}s...", backoff)
Message: 'Reconnecting in {}s...'
Arguments: (4.5,)
marathon_lb: Connection error(None): None
marathon_lb: stopping event processor thread
```

**Comment by brndnmtthws** [comment]
Strange. Are you using SSL for Marathon? Is it a self-signed cert?

**Comment by Nihn** [comment]
Yes, I use ssl with sef-signed cert.

**Comment by brndnmtthws** [comment]
Maybe have a look at this:

https://stackoverflow.com/questions/10667960/python-requests-throwing-up-sslerror

**Comment by Nihn** [comment]
I know that error and I had it before but mounting `/etc/ssl/certs` with cert into container `/etc/ssl/certs` resolved issue in the marathon-lb prior to `1.2.1`.

**Comment by brndnmtthws** [comment]
The only thing that changed which might possibly affect this is that the default cert path was switched from `/etc/ssl/mesosphere.com.pem` to `/etc/ssl/cert.pem`. I'm not sure why that would affect the Python requests library, other than the fact that the CA file might be missing.

**Comment by Nihn** [comment]
Ok, we managed to resolve this. For the record:

* Set env var `REQUESTS_CA_BUNDLE`, so that requests uses `/etc/ssl/certs/` instead of it's builtin bundle.
* Mounted `/usr/local/share/ca-certificates` dir inside the container, as some entries in `/etc/ssl/certs` are just symlinks to the former one.

**Comment by brndnmtthws** [comment]
Good to know, thanks for reporting that!
