### ISSUE TITLE
HA proxy error datetime.datetime

### ISSUE THREAD

**Issue by maauso** [mesosphere/marathon-lb#185]
Hi, 
I try to run a deployment with "zero downtime deployment" using blue green concepts.
I run the example that I can find in documentation, the steps are
1.- Deploy in Marathon 1-nginx.json
2.- Run ./bluegreen_deploy.py -j tests/1-nginx.json -m http://adm-mesos:8080 -f -l http://haproxy:9090
The procedure ends with time out and in the HA log we can see 

marathon_lb: Unexpected error!
Traceback (most recent call last):
  File "/marathon-lb/marathon_lb.py", line 1172, in do_reset
    self.__apps = get_apps(self.__marathon)
  File "/marathon-lb/marathon_lb.py", line 989, in get_apps
    if prev_date < cur_date:
TypeError: unorderable types: str() < datetime.datetime()

**Comment by maauso** [comment]
The steps are not correct
