### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by trav-pf** [mesosphere/marathon-lb#357]
Deployment failed again with same error as last time: #355. 

I tried again today with available version 1.4.1 from Universe.

Services-Log:

```
--container="mesos-7752f3ad-2124-481c-bb61-808cf44d4486-S6.bba7b383-b7d4-4686-ac49-f885810c5ba4" --docker="docker" --docker_socket="/var/run/docker.sock" --help="false" --initialize_driver_logging="true" --launcher_dir="/opt/mesosphere/packages/mesos--19a545facb66e57dfe2bb905a001a58b7eaf6004/libexec/mesos" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/var/lib/mesos/slave/slaves/7752f3ad-2124-481c-bb61-808cf44d4486-S6/frameworks/7752f3ad-2124-481c-bb61-808cf44d4486-0001/executors/marathon-lb.ac04828b-99ac-11e6-b566-70b3d5800007/runs/bba7b383-b7d4-4686-ac49-f885810c5ba4" --stop_timeout="20secs"
--container="mesos-7752f3ad-2124-481c-bb61-808cf44d4486-S6.bba7b383-b7d4-4686-ac49-f885810c5ba4" --docker="docker" --docker_socket="/var/run/docker.sock" --help="false" --initialize_driver_logging="true" --launcher_dir="/opt/mesosphere/packages/mesos--19a545facb66e57dfe2bb905a001a58b7eaf6004/libexec/mesos" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/var/lib/mesos/slave/slaves/7752f3ad-2124-481c-bb61-808cf44d4486-S6/frameworks/7752f3ad-2124-481c-bb61-808cf44d4486-0001/executors/marathon-lb.ac04828b-99ac-11e6-b566-70b3d5800007/runs/bba7b383-b7d4-4686-ac49-f885810c5ba4" --stop_timeout="20secs"
Registered docker executor on 10.64.56.3
Starting task marathon-lb.ac04828b-99ac-11e6-b566-70b3d5800007
setting sysctl params to: net.ipv4.tcp_tw_reuse=1 net.ipv4.tcp_fin_timeout=30 net.ipv4.tcp_max_syn_backlog=10240 net.ipv4.tcp_max_tw_buckets=400000 net.ipv4.tcp_max_orphans=60000 net.core.somaxconn=10000
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_max_syn_backlog = 10240
net.ipv4.tcp_max_tw_buckets = 400000
net.ipv4.tcp_max_orphans = 60000
net.core.somaxconn = 10000
Reloading haproxy
cat: /tmp/haproxy.pid: No such file or directory
[ALERT] 297/054245 (184) : Could not open configuration file /marathon-lb/haproxy.cfg : No such file or directory
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_APPID_HEAD
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ACL_WITH_PATH
marathon_lb: setting default value for HAPROXY_HTTP_BACKEND_ACL_ALLOW_DENY
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ROUTING_ONLY_WITH_PATH_AND_AUTH
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_ACL_ONLY_WITH_PATH
marathon_lb: setting default value for HAPROXY_TCP_BACKEND_ACL_ALLOW_DENY
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_ACL_WITH_AUTH_AND_PATH
marathon_lb: setting default value for HAPROXY_MAP_HTTP_FRONTEND_ACL_ONLY
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ACL
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_ACL
marathon_lb: setting default value for HAPROXY_TCP_BACKEND_NETWORK_ALLOWED_ACL
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ROUTING_ONLY
marathon_lb: setting default value for HAPROXY_FRONTEND_BACKEND_GLUE
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_ROUTING_ONLY_WITH_PATH_AND_AUTH
marathon_lb: setting default value for HAPROXY_HTTP_BACKEND_REDIR
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_AUTH_REQUEST_ONLY
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_ACL_WITH_AUTH
marathon_lb: setting default value for HAPROXY_BACKEND_HTTP_OPTIONS
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ACL_WITH_AUTH
marathon_lb: setting default value for HAPROXY_MAP_HTTP_FRONTEND_APPID_ACL
marathon_lb: setting default value for HAPROXY_BACKEND_SERVER_HTTP_HEALTHCHECK_OPTIONS
marathon_lb: setting default value for HAPROXY_BACKEND_HTTP_HEALTHCHECK_OPTIONS
marathon_lb: setting default value for HAPROXY_HTTP_BACKEND_NETWORK_ALLOWED_ACL
marathon_lb: setting default value for HAPROXY_MAP_HTTPS_FRONTEND_ACL
marathon_lb: setting default value for HAPROXY_MAP_HTTP_FRONTEND_ACL
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ROUTING_ONLY_WITH_AUTH
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ROUTING_ONLY_WITH_PATH
marathon_lb: setting default value for HAPROXY_BACKEND_REDIRECT_HTTP_TO_HTTPS
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ACL_WITH_AUTH_AND_PATH
marathon_lb: setting default value for HAPROXY_HEAD
marathon_lb: setting default value for HAPROXY_BACKEND_SERVER_TCP_HEALTHCHECK_OPTIONS
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ACL_ONLY
marathon_lb: setting default value for HAPROXY_HTTP_BACKEND_PROXYPASS_GLUE
marathon_lb: setting default value for HAPROXY_BACKEND_HEAD
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ACL_ONLY_WITH_PATH_AND_AUTH
marathon_lb: setting default value for HAPROXY_HTTP_BACKEND_REVPROXY_GLUE
marathon_lb: setting default value for HAPROXY_USERLIST_HEAD
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_APPID_ACL
marathon_lb: setting default value for HAPROXY_BACKEND_STICKY_OPTIONS
marathon_lb: setting default value for HAPROXY_BACKEND_SERVER_OPTIONS
marathon_lb: setting default value for HAPROXY_BACKEND_REDIRECT_HTTP_TO_HTTPS_WITH_PATH
marathon_lb: setting default value for HAPROXY_BACKEND_TCP_HEALTHCHECK_OPTIONS
marathon_lb: setting default value for HAPROXY_BACKEND_HSTS_OPTIONS
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_AUTH_ACL_ONLY
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_ACL_ONLY_WITH_PATH
marathon_lb: setting default value for HAPROXY_HTTP_FRONTEND_HEAD
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_ACL_WITH_PATH
marathon_lb: setting default value for HAPROXY_FRONTEND_HEAD
marathon_lb: setting default value for HAPROXY_HTTPS_FRONTEND_HEAD
marathon_lb: starting event processor thread
marathon_lb: fetching apps
marathon_lb: SSE Active, trying fetch events from http://master.mesos:8080/v2/events
marathon_lb: GET http://master.mesos:8080/v2/apps?embed=apps.tasks
marathon_lb: got apps ['/etcd', '/marathon-lb', '/my-docker-task', '/frontend', '/calico-install-framework', '/database']
marathon_lb: Unexpected error!
Traceback (most recent call last):
  File "/marathon-lb/marathon_lb.py", line 1520, in do_reset
    self.__apps = get_apps(self.__marathon)
  File "/marathon-lb/marathon_lb.py", line 1349, in get_apps
    service_ports = SERVICE_PORT_ASSIGNER.get_service_ports(app)
  File "/marathon-lb/utils.py", line 121, in get_service_ports
    portMappings))
TypeError: 'NoneType' object is not iterable
marathon_lb: received event of type event_stream_attached
marathon_lb: received event of type failed_health_check_event
marathon_lb: received event of type failed_health_check_event
marathon_lb: received event of type failed_health_check_event
Received killTask for task marathon-lb.ac04828b-99ac-11e6-b566-70b3d5800007
marathon_lb: received event of type unhealthy_task_kill_event
```

**Comment by brndnmtthws** [comment]
Change the image tag to `:latest`, and try that.

**Comment by trav-pf** [comment]
The question for me is: Why is the newest version not automatically in the mesophere-universe and deployable via GUI?

On the other hand: what does it mean for a non-developer in steps to change the image of marathon-lb?

**Comment by brndnmtthws** [comment]
I haven't yet published a release with that change.

In the Marathon UI, you can simply change the image tag in the container definition. You could also just wait for the next release.

**Comment by trav-pf** [comment]
I edited under "Services" the image tag for marathon-lb and also checked "Force pull image on launch". 
Now the services details shows this for container configuration:
{
    "type": "DOCKER",
    "docker": {
        "image": "mesosphere/marathon-lb:latest",
        "network": "HOST",
        "privileged": true,
        "force_pull_image": true
    }
}

But the logs stil have the same errors as before.

**Comment by brndnmtthws** [comment]
I don't see how that error can be triggered with the current code. Can you please validate that you're actually running the latest build?

**Comment by trav-pf** [comment]
How can I validate the running if there is no service deployed (means being unhealthy)?

When I look at the processes on a public agent (`docker ps`) there is no marathon-lb container.

**Comment by brndnmtthws** [comment]
If you SSH into the machine, you should be able to list all the docker images with `docker images -a`, then you can check the code is correct by running `docker run --entrypoint=/bin/bash <image ID>` and comparing `utils.py` inside the container to what's in the git repo.

**Comment by trav-pf** [comment]
In both of the public agents there is an image with the tag "latest":
`mesosphere/marathon-lb   latest              58996017804c        7 hours ago         168.1 MB`

If I start the service via GUI there is a new container showing up:
`077b16a9d399        mesosphere/marathon-lb:latest   "/marathon-lb/run sse"   57 seconds ago      Up 55 seconds                           mesos-7752f3ad-2124-481c-bb61-808cf44d4486-S6.048dd301-edf9-4905-a5be-c40fcfcc661c`
After a while this container is gone and a new one has started up. In the end no container survives.

If I start the container with `docker run` it lives for about 60-80 seconds and is then gone. When I look into the container, I can see this:

```
[root@lb01 ~]# docker exec a7d996a4359d ls -l
total 304
-rw-r--r--. 1 root root 11358 Oct 26 22:01 LICENSE
-rw-r--r--. 1 root root 41963 Oct 26 22:01 Longhelp.md
-rw-r--r--. 1 root root 25085 Oct 26 22:01 README.md
drwxr-xr-x. 2 root root  4096 Oct 27 06:24 __pycache__
lrwxrwxrwx. 1 root root     6 Oct 26 22:01 bluegreen_deploy.py -> zdd.py
-rwxr-xr-x. 1 root root  1284 Oct 26 22:01 build-haproxy.sh
-rw-r--r--. 1 root root  4498 Oct 26 22:01 common.py
-rw-r--r--. 1 root root 57231 Oct 26 22:01 config.py
-rw-r--r--. 1 root root   906 Oct 26 22:01 getconfig.lua
-rw-r--r--. 1 root root  1638 Oct 26 22:01 getmaps.lua
-rw-r--r--. 1 root root   666 Oct 26 22:01 getpids.lua
-rw-r--r--. 1 root root   723 Oct 26 22:01 lrucache.py
-rwxr-xr-x. 1 root root 72982 Oct 26 22:01 marathon_lb.py
-rw-r--r--. 1 root root    62 Oct 26 22:01 requirements.txt
-rwxr-xr-x. 1 root root  3568 Oct 26 22:01 run
drwxr-xr-x. 4 root root    29 Oct 27 06:24 service
-rw-r--r--. 1 root root  1309 Oct 26 22:01 signalmlb.lua
drwxr-xr-x. 2 root root    21 Oct 26 22:01 templates
-rw-r--r--. 1 root root  8640 Oct 26 22:01 utils.py
-rwxr-xr-x. 1 root root 29177 Oct 26 22:01 zdd.py
-rw-r--r--. 1 root root  2721 Oct 26 22:01 zdd_exceptions.py
```

**Comment by trav-pf** [comment]
With tag "latest" the output of the services log is different in the lines numbering of marathon.py:

```
--container="mesos-7752f3ad-2124-481c-bb61-808cf44d4486-S0.f33cc406-c45b-4544-9305-ab12f7eedb6f" --docker="docker" --docker_socket="/var/run/docker.sock" --help="false" --initialize_driver_logging="true" --launcher_dir="/opt/mesosphere/packages/mesos--19a545facb66e57dfe2bb905a001a58b7eaf6004/libexec/mesos" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/var/lib/mesos/slave/slaves/7752f3ad-2124-481c-bb61-808cf44d4486-S0/frameworks/7752f3ad-2124-481c-bb61-808cf44d4486-0001/executors/marathon-lb.cf949d37-9cd1-11e6-b566-70b3d5800007/runs/f33cc406-c45b-4544-9305-ab12f7eedb6f" --stop_timeout="20secs"
--container="mesos-7752f3ad-2124-481c-bb61-808cf44d4486-S0.f33cc406-c45b-4544-9305-ab12f7eedb6f" --docker="docker" --docker_socket="/var/run/docker.sock" --help="false" --initialize_driver_logging="true" --launcher_dir="/opt/mesosphere/packages/mesos--19a545facb66e57dfe2bb905a001a58b7eaf6004/libexec/mesos" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/var/lib/mesos/slave/slaves/7752f3ad-2124-481c-bb61-808cf44d4486-S0/frameworks/7752f3ad-2124-481c-bb61-808cf44d4486-0001/executors/marathon-lb.cf949d37-9cd1-11e6-b566-70b3d5800007/runs/f33cc406-c45b-4544-9305-ab12f7eedb6f" --stop_timeout="20secs"

...
2016-10-28 05:46:24,634 marathon_lb: GET http://master.mesos:8080/v2/apps?embed=apps.tasks
2016-10-28 05:46:24,635 marathon_lb: got apps ['/etcd', '/marathon-lb', '/my-docker-task', '/frontend', '/calico-install-framework', '/database']
2016-10-28 05:46:24,640 marathon_lb: Unexpected error!
Traceback (most recent call last):
  File "/marathon-lb/marathon_lb.py", line 1524, in do_reset
    self.__apps = get_apps(self.__marathon)
  File "/marathon-lb/marathon_lb.py", line 1353, in get_apps
    service_ports = SERVICE_PORT_ASSIGNER.get_service_ports(app)
  File "/marathon-lb/utils.py", line 137, in get_service_ports
    _, task_ports = get_task_ip_and_ports(app, task)
  File "/marathon-lb/utils.py", line 219, in get_task_ip_and_ports
    portMappings))
TypeError: 'NoneType' object is not iterable
2016-10-28 05:46:28,547 marathon_lb: received event of type event_stream_attached
2016-10-28 05:46:33,567 marathon_lb: received event of type failed_health_check_event
2016-10-28 05:46:33,567 marathon_lb: received event of type failed_health_check_event
2016-10-28 05:46:33,574 marathon_lb: received event of type unhealthy_task_kill_event
2016-10-28 05:46:33,814 marathon_lb: received event of type status_update_event
2016-10-28 05:46:33,814 marathon_lb: fetching apps
2016-10-28 05:46:33,830 marathon_lb: GET http://master.mesos:8080/v2/apps?embed=apps.tasks
2016-10-28 05:46:33,831 marathon_lb: got apps ['/etcd', '/marathon-lb', '/my-docker-task', '/frontend', '/calico-install-framework', '/database']
2016-10-28 05:46:33,836 marathon_lb: Unexpected error!
Traceback (most recent call last):
  File "/marathon-lb/marathon_lb.py", line 1524, in do_reset
    self.__apps = get_apps(self.__marathon)
  File "/marathon-lb/marathon_lb.py", line 1353, in get_apps
    service_ports = SERVICE_PORT_ASSIGNER.get_service_ports(app)
  File "/marathon-lb/utils.py", line 137, in get_service_ports
    _, task_ports = get_task_ip_and_ports(app, task)
  File "/marathon-lb/utils.py", line 219, in get_task_ip_and_ports
    portMappings))
TypeError: 'NoneType' object is not iterable
2016-10-28 05:46:52,706 marathon_lb: received event of type status_update_event
2016-10-28 05:46:52,706 marathon_lb: fetching apps
2016-10-28 05:46:52,721 marathon_lb: GET http://master.mesos:8080/v2/apps?embed=apps.tasks
2016-10-28 05:46:52,722 marathon_lb: got apps ['/etcd', '/marathon-lb', '/my-docker-task', '/frontend', '/calico-install-framework', '/database']
2016-10-28 05:46:52,727 marathon_lb: Unexpected error!
Traceback (most recent call last):
  File "/marathon-lb/marathon_lb.py", line 1524, in do_reset
    self.__apps = get_apps(self.__marathon)
  File "/marathon-lb/marathon_lb.py", line 1353, in get_apps
    service_ports = SERVICE_PORT_ASSIGNER.get_service_ports(app)
  File "/marathon-lb/utils.py", line 137, in get_service_ports
    _, task_ports = get_task_ip_and_ports(app, task)
  File "/marathon-lb/utils.py", line 219, in get_task_ip_and_ports
    portMappings))
TypeError: 'NoneType' object is not iterable
2016-10-28 05:47:22,926 marathon_lb: received event of type event_stream_detached
2016-10-28 05:47:32,968 marathon_lb: received event of type failed_health_check_event
2016-10-28 05:47:32,968 marathon_lb: received event of type failed_health_check_event
2016-10-28 05:47:32,968 marathon_lb: received event of type failed_health_check_event
Received killTask for task marathon-lb.cf949d37-9cd1-11e6-b566-70b3d5800007
2016-10-28 05:47:32,980 marathon_lb: received event of type unhealthy_task_kill_event
```

**Comment by brndnmtthws** [comment]
Ah, I see. This is a different error entirely.

**Comment by brndnmtthws** [comment]
Can you test the `fix-ip-per-task-missing-portmapping` image tag and see if that resolves it?

**Comment by trav-pf** [comment]
Yes, marathon-lb 1.4.2 is running now. Thank you!
