### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by Arkan** [mesosphere/marathon-lb#39]
Hi there,

I just noticed a crash in the python script. Here is the stack trace

```
marathon-lb: skipping empty message
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    58    0    58    0     0   3635      0 --:--:-- --:--:-- --:--:-- 58000
<html><body><h1>200 OK</h1>
Service ready.
</body></html>
Traceback (most recent call last):
  File "/marathon-lb/marathon_lb.py", line 1158, in <module>
    not args.dont_bind_http_https, args.ssl_certs)
  File "/marathon-lb/marathon_lb.py", line 1085, in process_sse_events
    for event in events:
  File "/usr/local/lib/python3.4/dist-packages/sseclient.py", line 60, in __next__
    nextchar = next(self.resp.iter_content(decode_unicode=True))
  File "/usr/lib/python3/dist-packages/requests/utils.py", line 329, in stream_decode_response_unicode
    for chunk in iterator:
  File "/usr/lib/python3/dist-packages/requests/models.py", line 653, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 256, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 186, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.4/http/client.py", line 500, in read
    return super(HTTPResponse, self).read(amt)
  File "/usr/lib/python3.4/http/client.py", line 539, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by brndnmtthws** [comment]
Have a look at #41, which should prevent a crash when the connection is lost.
