### ISSUE TITLE
local variable 'cur_date' referenced before assignment

### ISSUE THREAD

**Issue by tanyehzheng** [mesosphere/marathon-lb#393]
https://github.com/mesosphere/marathon-lb/issues/366
If the HAPROXY_DEPLOYMENT_GROUP exists but not the HAPROXY_DEPLOYMENT_STARTED_AT  label  

2017-01-05 11:22:34,166 marathon_lb: Unexpected error!
Traceback (most recent call last):
  File "/marathon-lb/marathon_lb.py", line 1526, in do_reset
    self.__apps = get_apps(self.__marathon)
  File "/marathon-lb/marathon_lb.py", line 1275, in get_apps
    if prev_date < cur_date:
UnboundLocalError: local variable 'cur_date' referenced before assignment

After adding the HAPROXY_DEPLOYMENT_STARTED_AT label but not the HAPROXY_DEPLOYMENT_TARGET_INSTANCES label   

2017-01-05 11:26:16,638 marathon_lb: Unexpected error!
Traceback (most recent call last):
  File "/marathon-lb/marathon_lb.py", line 1526, in do_reset
    self.__apps = get_apps(self.__marathon)
  File "/marathon-lb/marathon_lb.py", line 1294, in get_apps
    int(new['labels']['HAPROXY_DEPLOYMENT_TARGET_INSTANCES'])
KeyError: 'HAPROXY_DEPLOYMENT_TARGET_INSTANCES'

**Comment by brndnmtthws** [comment]
Give the `fix-missing-date-in-zdd` image tag a try.

**Comment by tanyehzheng** [comment]
@brndnmtthws it fixes the first issue but not the second.  
After adding the HAPROXY_DEPLOYMENT_STARTED_AT label, it assumes the HAPROXY_DEPLOYMENT_TARGET_INSTANCES label is also set which may be false.

**Comment by brndnmtthws** [comment]
Generally speaking, if you're using ZDD you should _only_ deploy apps with ZDD.
