### ISSUE TITLE
HTTPS Marathon connection fails on SSE event streaming

### ISSUE THREAD

**Issue by shayangz** [mesosphere/marathon-lb#466]
We run our Marathon installation in HTTPS only configuration using a custom internal CA.

If we launch marathon-lb with `--marathon-ca-cert` option, the calls to `/v2/apps?embed=apps.tasks` succeed but calls to subscribe to SSE (`/v2/events`) fail with `pycurl.error: (77, '')` reflecting a SSL cert verification issue.

Here is the log output of when the failure occurs:

```
2017-06-09 21:35:46,387 marathon_lb: starting event processor thread
2017-06-09 21:35:46,387 marathon_lb: SSE Active, trying fetch events from https://10.0.2.15:8080/v2/events
2017-06-09 21:35:46,388 marathon_lb: fetching apps
2017-06-09 21:35:46,488 marathon_lb: GET https://10.0.2.15:8080/v2/apps?embed=apps.tasks
2017-06-09 21:35:46,489 marathon_lb: got apps []
2017-06-09 21:35:46,489 marathon_lb: generating config
2017-06-09 21:35:46,490 marathon_lb: HAProxy dir is /etc/haproxy
2017-06-09 21:35:46,490 marathon_lb: reading running config from /etc/haproxy/haproxy.cfg
2017-06-09 21:35:46,492 marathon_lb: skipping reload: config unchanged
2017-06-09 21:35:46,492 marathon_lb: updating tasks finished, took 0.10413980484008789 seconds
2017-06-09 21:35:46,493 marathon_lb: Caught exception
Traceback (most recent call last):
  File "marathon_lb.py", line 1749, in <module>
    process_sse_events(marathon, processor)
  File "marathon_lb.py", line 1654, in process_sse_events
    for event in events:
  File "marathon_lb.py", line 237, in get_event_stream
    for line in resp.iter_lines():
  File "/opt/marathon_lb/utils.py", line 230, in _split_lines_from_chunks
    for chunk in chunks:
  File "/opt/marathon_lb/utils.py", line 215, in _iter_chunks
    self._check_curl_errors()
  File "/opt/marathon_lb/utils.py", line 219, in _check_curl_errors
    raise pycurl.error(*f[1:])
pycurl.error: (77, '')
```

if we don't provide the  `--marathon-ca-cert` option, everything works but as the warning suggests we are not verifying the Marathon SSL cert (which we want to do).

```
2017-06-09 21:40:31,721 marathon_lb: starting event processor thread
2017-06-09 21:40:31,721 marathon_lb: SSE Active, trying fetch events from https://10.0.2.15:8080/v2/events
2017-06-09 21:40:31,722 marathon_lb: fetching apps
/opt/marathon_lb/lib/python3.5/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2017-06-09 21:40:31,849 marathon_lb: GET https://10.0.2.15:8080/v2/apps?embed=apps.tasks
2017-06-09 21:40:31,850 marathon_lb: got apps []
2017-06-09 21:40:31,850 marathon_lb: generating config
2017-06-09 21:40:31,850 marathon_lb: HAProxy dir is /etc/haproxy
2017-06-09 21:40:31,851 marathon_lb: reading running config from /etc/haproxy/haproxy.cfg
2017-06-09 21:40:31,852 marathon_lb: skipping reload: config unchanged
2017-06-09 21:40:31,853 marathon_lb: updating tasks finished, took 0.13069486618041992 seconds
2017-06-09 21:40:31,893 marathon_lb: received event of type event_stream_attached
```

I am not a python expert but looking at the code it looks like the `--marathon-ca-cert` file is being passed to the curl client the same way both in regular GET calls to `/v2/apps` and in the CurlMulti calls to `v2/events` for SSE.

Any pointers would be appreciated.

**Comment by jkoelker** [comment]
I believe this was fixed in v1.5.1 via https://github.com/mesosphere/marathon-lb/commit/f8d0724c090cc1da53a79a5c69721a83ac3affd1. Please let me know if this is not correct.
