### ISSUE TITLE
Using customHAPROXY_HTTPS_FRONTEND_HEAD unexpected error

### ISSUE THREAD

**Issue by amramtamir** [mesosphere/marathon-lb#534]
Hi,
I am receiving this error on marathon-lb v1.10.0 , I am using a custom HAPROXY_HTTPS_FRONTEND_HEAD which works in v1.4.2.
any ideas ?

The template:
frontend marathon_https_in
  bind *:443 ssl crt /etc/ssl/cert.pem
  mode http
  capture request header Host len 32
  capture request header User-Agent len 64

The error:
2017-12-26 07:03:41,559 marathon_lb: generating config
2017-12-26 07:03:41,560 marathon_lb: Unexpected error!
Traceback (most recent call last):
  File "/marathon-lb/marathon_lb.py", line 1557, in do_reset
    self.__haproxy_map)
  File "/marathon-lb/marathon_lb.py", line 1482, in regenerate_config
    app_map_array, config_file)
  File "/marathon-lb/marathon_lb.py", line 345, in config
    sslCerts=" ".join(map(lambda cert: "crt " + cert, _ssl_certs))
KeyError: 'option'
[/marathon-lb/service/haproxy ./run] addFirewallRules done
[/marathon-lb/service/haproxy ./run] Saving the current HAProxy state
[/marathon-lb/service/haproxy ./run] Done saving the current HAProxy state
cat: /tmp/haproxy.pid: No such file or directory
[/marathon-lb/service/haproxy ./run] LATEST_HAPROXY_PID: []
[/marathon-lb/service/haproxy ./run] /marathon-lb/haproxy_wrapper.py /usr/local/sbin/haproxy -D -p /tmp/haproxy.pid -f /marathon-lb/haproxy.cfg -sf  200>&-
2017-12-26 07:03:41,660 haproxy_wrapper: create_haproxy_pipe called
2017-12-26 07:03:41,660 haproxy_wrapper: create_haproxy_pipe done
2017-12-26 07:03:41,661 haproxy_wrapper: wait_on_haproxy_pipe called
[ALERT] 359/070341 (203) : Cannot open configuration file/directory /marathon-lb/haproxy.cfg : No such file or directory
2017-12-26 07:03:41,664 haproxy_wrapper: close_and_swallow called
2017-12-26 07:03:41,665 haproxy_wrapper: close_and_swallow successful
2017-12-26 07:03:41,665 haproxy_wrapper: close_and_swallow called
2017-12-26 07:03:41,665 haproxy_wrapper: close_and_swallow swallow OSError: [Errno 9] Bad file descriptor
2017-12-26 07:03:41,665 haproxy_wrapper: wait_on_haproxy_pipe done (False)
[/marathon-lb/service/haproxy ./run] exit code: 0
[/marathon-lb/service/haproxy ./run] Removing firewall rules with removeFirewallRules
[/marathon-lb/service/haproxy ./run] removeFirewallRules done
[/marathon-lb/service/haproxy ./run] Reload finished
2017-12-26 07:04:03,587 marathon_lb: received event of type failed_health_check_event
2017-12-26 07:04:44,852 marathon_lb: received event of type failed_health_check_event
2017-12-26 07:04:49,873 marathon_lb: received event of type failed_health_check_event
2017-12-26 07:04:54,893 marathon_lb: received event of type failed_health_check_event
2017-12-26 07:04:54,893 marathon_lb: received event of type unhealthy_task_kill_event
Received killTask for task marathon-lb-internal.e682be0f-ea0a-11e7-b5ee-70b3d580000a

**Comment by justinrlee** [comment]
Hey, if you've just updated the Docker image tag for Marathon-LB (moving from MLB 1.4.2 to 1.10.0), there are a handful of new external configuration options that have to go into the Marathon JSON definition.  Rather than just dropping in the new image tag, may be re-installing Marathon-LB (or ideally, if you have multiple public agent nodes, scaling the current instance count to one, deploying a new instance with a different name).

**Comment by jkoelker** [comment]
Hi I'm working on cleaning up the marathon-lb repo. Since this issue is pretty old and there have been a few releases in between, I'm going to close this issue for now. If this is still an issue with the latest 1.12.x series please let me know and reopen this. If possible please provide the full deployment files.
