### ISSUE TITLE
Exception occured every two minites

### ISSUE THREAD

**Issue by liuyi01** [mesosphere/marathon-lb#565]
I use marathon-lb in docker mode, apps often return 503 error code when restart witch is ok when a long time passed. I found the error logs below:
Traceback (most recent call last):
  File "/marathon-lb/marathon_lb.py", line 1912, in <module>
    for event in events:
  File "/marathon-lb/marathon_lb.py", line 243, in iter_events
    for line in stream.iter_lines():
  File "/marathon-lb/utils.py", line 241, in _split_lines_from_chunks
    for chunk in chunks:
  File "/marathon-lb/utils.py", line 219, in _iter_chunks
    self._check_status_code()
  File "/marathon-lb/utils.py", line 206, in _check_status_code
    raise Exception(str(self.status_code) + ' ' + self.url)
Exception: 504 https://www.xxx.com/v2/events?plan-format=light&event_type=status_update_event&event_type=health_status_changed_event&event_type=api_post_event
2018-03-26 07:45:26,983 marathon_lb: Reconnecting in 2.800501915287155s..

**Comment by liuyi01** [comment]
I found the problem, nginx config result in this
