### ISSUE TITLE
Running marathon-lb as docker wont start with latest build (group_https_by_vhost)

### ISSUE THREAD

**Issue by frothlauf** [mesosphere/marathon-lb#572]
Hey Guys,

just setup a new cluster, everything was working fine until i got to marathon-lb which is running within docker. A simple (without all the parameters i am usually using) docker run command fails with the following message:

# docker run -d -e PORTS=80,9090 mesosphere/marathon-lb poll --group external

2018-04-10 09:27:42,272 marathon_lb: setting default value for HAPROXY_TCP_BACKEND_ACL_ALLOW_DENY
Traceback (most recent call last):
  File "/marathon-lb/marathon_lb.py", line 2105, in <module>
    args.haproxy_map)
TypeError: regenerate_config() missing 1 required positional argument: 'group_https_by_vhost'
[/marathon-lb/service/haproxy ./run] Reload finished

Did you experience similar behaviour? I am running v1.11.3 now again and everything seems to be running just fine. Am I missing something? Thanks in advance!

**Comment by hodeh** [comment]
I am facing the same issue when pulling the latest marathon-lb , i am getting this:

Traceback (most recent call last):


  File "/marathon-lb/marathon_lb.py", line 2105, in <module>


    args.haproxy_map)


TypeError: regenerate_config() missing 1 required positional argument: 'group_https_by_vhost'

**Comment by drewkerrigan** [comment]
I've addressed this in https://github.com/mesosphere/marathon-lb/pull/573 which will be included in the next release.
