### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by daniyel** [mesosphere/marathon-lb#603]
Hi.

We had an issue recently with **marathon-lb**, where everything seemed to be working ok, but suddenly none of the services where available.

Version of **marathon-lb** is 1.12.3 and DC/OS version is 1.9.0. We have two instances of LB running, one on each public agent node. We used default settings (1GiB memory and 2 CPU) when installing from DC/OS Universe.

We checked the error logs and we found this entries inside:

```
2018-10-10 07:26:38,524 marathon_lb: running config/map is different from generated config - reloading
2018-10-10 07:26:38,525 marathon_lb: Unexpected error!
Traceback (most recent call last):
  File "/marathon-lb/marathon_lb.py", line 1951, in do_reset
    self.__group_https_by_vhost)
  File "/marathon-lb/marathon_lb.py", line 1783, in regenerate_config
    haproxy_map)
  File "/marathon-lb/marathon_lb.py", line 1466, in compareWriteAndReloadConfig
    app_map_string, app_map_file, haproxy_map):
  File "/marathon-lb/marathon_lb.py", line 1307, in writeConfigAndValidate
    domain_map_file)
  File "/marathon-lb/marathon_lb.py", line 1348, in writeReplacementTempFile
    fd, tempFile = mkstemp()
  File "/usr/lib/python3.6/tempfile.py", line 483, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.6/tempfile.py", line 401, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 28] No space left on device: '/tmp/tmpe8zywe86'
```

After we restarted the instances manually, everything was working as expected. We checked Disk, Memory and CPU allocation of DC/OS and there is still plenty of everything.

Best regards.

**Comment by daniyel** [comment]
Hi.

So I found out that there was nothing set or limited concerning logs in the `/etc/docker/daemon.json`. To prevent `xyz-json.log` logs to exceed the size of a disk, you can set following settings in the `daemon.json` and adjust the values according to your needs:

```
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "10"
  }
}
```
