### ISSUE TITLE
[redux] 'Module_six_moves_urllib' object has no attribute 'urlparse'

### ISSUE THREAD

**Issue by scalp42** [mesosphere/marathon-lb#73]
Using `Python 3.4.3` and a3a080ecd4a5467c6095052f20d3818a5e480a6d commit:

```
Traceback (most recent call last):
  File "marathon_lb.py", line 1181, in <module>
    not args.dont_bind_http_https, args.ssl_certs)
  File "marathon_lb.py", line 1095, in run_server
    listen_uri = urllib.urlparse(listen_addr)
AttributeError: 'Module_six_moves_urllib' object has no attribute 'urlparse'
```

The original issue is: https://github.com/mesosphere/marathon-lb/issues/54

Possibly related: https://github.com/mesosphere/marathon-lb/pull/56

**Comment by brndnmtthws** [comment]
Is this still an issue? Please reopen if so.
