### ISSUE TITLE
marathon-lb stoped when upgrade marathon

### ISSUE THREAD

**Issue by heww** [mesosphere/marathon-lb#95]
When I upgrade marathon, eg from 0.14.0 to 0.14.1, then marathon-lb will stopped and I get 503 for apps run in marathon. Here is the stderr when marathon-lb stopped.

And, the args used for marathon-lb is: `pool -m http://marathon.mesos:8080 --health-check --group external`

```shell
Generating RSA private key, 2048 bit long modulus
....................................................................................................................+++
.+++
e is 65537 (0x10001)
Signature ok
subject=/CN=*
Getting Private key
marathon_lb: fetching apps
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 308, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.4/http/client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 924, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 859, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 154, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 133, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 87, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 559, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 624, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 308, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.4/http/client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 924, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 859, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 154, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 133, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 87, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/marathon-lb/marathon_lb.py", line 1368, in <module>
    regenerate_config(get_apps(marathon), args.haproxy_config, args.group,
  File "/marathon-lb/marathon_lb.py", line 966, in get_apps
    apps = marathon.list()
  File "/marathon-lb/marathon_lb.py", line 529, in list
    params={'embed': 'apps.tasks'})["apps"]
  File "/marathon-lb/marathon_lb.py", line 516, in api_req
    return self.api_req_raw(method, path, self.__auth, **kwargs).json()
  File "/marathon-lb/marathon_lb.py", line 502, in api_req_raw
    **kwargs
  File "/usr/lib/python3/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
```

**Comment by lloesche** [comment]
ConnectionRefusedError sounds like Marathon isn't listening on the URL specified.

What does a
```
curl http://marathon.mesos:8080/v2/apps
```
output?

**Comment by heww** [comment]
When I upgrade marathon, I will stop marathon service in masters and start new version marathon one by one,  when the leader of marathon stopped, marathon.mesos:8080 will be not accessible so errors above happened for marathon.mesos is resolved by mesos-dns and there is cache in mesos-dns.

**Comment by lloesche** [comment]
Understood. Good that the problem resolved itself.
